### ISSUE TITLE
maven link for mysql-connector is broken

### ISSUE THREAD

**Issue by charlseo** [martinprobson/vagrant-hadoop-hive-spark#18]
First of all, thx for the great work. 

I found the maven repo for mysql-connector is old and not available. 
This should address it. 

JAVA_MYSQL_CONNECTOR_DOWNLOAD=https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/${JAVA_MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${JAVA_MYSQL_CONNECTOR_VERSION}.jar

**Comment by martinprobson** [comment]
Many thanks. Have updated common.sh to point to the new Maven repo.
