### ISSUE TITLE
vim.tar missing

### ISSUE THREAD

**Issue by rmxhaha** [martinprobson/vagrant-hadoop-hive-spark#2]
I don't really know what vim.tar is doing it doesn't seem to be doing anything but it causing an error. The script finalize-ubuntu.sh called tar xf $VIM_RES_DIR/vim.tar which causes the error. Could you remove or explain how to get vim.tar ?

**Comment by martinprobson** [comment]
Hi, Yes, you are right :-) I will have a look at the scripts and amend.

**Comment by martinprobson** [comment]
VIM.tar removed from latest release (2.7.4.2)
