### ISSUE TITLE
curl fail to download doesn't cause error

### ISSUE THREAD

**Issue by rmxhaha** [martinprobson/vagrant-hadoop-hive-spark#3]
I was setting up this virtual machine yesterday and hadoop keep complaining about some class not existing. It turns out curl fail to download a complete hadoop-2.7.3.tar.gz. I don't know the characteristic of every linux downloder out there but is it possible to change curl with something that retry if it fail to download ? 

Thank you.

**Comment by martinprobson** [comment]
Hi rmxhaha,
Thanks for letting me know. Curl does have retry options, but what I should really do is verify the md5sum of the downloaded file. I will look into doing this and push a new commit once tested. Will leave this issue open until then.

**Comment by martinprobson** [comment]
curl now includes retry option in latest release 2.7.4.2
