### ISSUE TITLE
jps does not show any hadoop process

### ISSUE THREAD

**Issue by kirankumarhm** [martinprobson/vagrant-hadoop-hive-spark#4]
When I connect usinig putty and type in jps does not show any hadoop process

**Comment by martinprobson** [comment]
Hi 
You need to be running as root to see the hadoop processes running with jps. What happens if you type `sudo jps`?
You should also be able to see Yarn resource mgr page at `http://10.211.55.101:8088`.
If Yarn/HDFS does not seem to be up then logs can be checked in `/usr/local/hadoop/logs`

**Comment by kirankumarhm** [comment]
Thank you, I will try that... FYI ... Also I am trying to include HBase and Kafka I will update you once I success

**Comment by kirankumarhm** [comment]
unfortunately mysql configuration is NOT working after installation. If you could provide proper configuration that will be great helpful.

I am getting below error:

   node1: Allow root access from network...
   node1: /tmp/vagrant-shell: line 39: mysql: command not found
   node1: Create hive_metastore schema...
   node1: /tmp/vagrant-shell: line 41: mysql: command not found
   node1: Create hive meta-db user...
   node1: /tmp/vagrant-shell: line 43: mysql: command not found
   node1: grant permissions to hive meta-db user...
   node1: /tmp/vagrant-shell: line 45: mysql: command not found
   node1: Flush mysqld for changes to take effect...
   node1: /tmp/vagrant-shell: line 47: mysql: command not found
   node1: Restarting mysqld for changes to take effect...

**Comment by martinprobson** [comment]
The mysql configuration should be working fine, it maybe an issue when mysql was installed and configured. Please retry with the latest release and see if that helps.
