### ISSUE TITLE
Sqoop file not found in release 2.7.4.2

### ISSUE THREAD

**Issue by rkq** [martinprobson/vagrant-hadoop-hive-spark#6]
During setup, file http://mirror.ox.ac.uk/sites/rsync.apache.org/sqoop/1.4.6/sqoop-1.4.6.bin__hadoop-2.0.4-alpha.tar.gz not found

**Comment by martinprobson** [comment]
Thanks, sqoop has been updated to 1.4.7. Changed common.sh to reflect this. Fixed in release 2.7.4.3
